### ISSUE TITLE
Less-preview does not have recent Less versions available

### ISSUE THREAD

**Issue by SomMeri** [less/less-preview#6]

**Comment by seven-phases-max** [comment]
To be honest I'd like to update but I simply can't. OK, I did install that >500Mb of modules required to create this ~1kb page and can't get it to compile :) (most likely I miss something simple like some `jspm` or `aurelia` config/path to be set elsewhere, but I do not have too much time (nor too much motivation to be honest) to get too deep into the setup/debugging of frameworks I'm not going to use for anything else :().

**Comment by lukeapage** [comment]
Yeah sorry about this! The easiest thing is to search the deployed minifiied js for a version number and add in the new ones.

**Comment by seven-phases-max** [comment]
>The easiest thing is to search the deployed minifiied js for a version number and add in the new ones.

Indeed. I've pushed the quick-fix with https://github.com/less/less-preview/commit/ec0e6346de481af18d9935a7d8d06191f0948680, but so far I'm experiencing some glitches with it (probably it's not just the only array to be modified).

**Comment by seven-phases-max** [comment]
>Let me know if you can see these glitches too so I'll revert the update.

After a few more tests I decided to revert https://github.com/less/less-preview/commit/ec0e6346de481af18d9935a7d8d06191f0948680 as it's definitely something wrong there (maybe some 2.6.x changes are not quite compatible, further research needed).

**Comment by matthew-dean** [comment]
This is an old issue, but relevant since I re-tooled the site. Ideally, we would populate a dropdown with the last X versions, vs. having to rebuild the Less preview site.

**Comment by iChenLei** [comment]
closed by #11
